import React, { useState, useEffect, type FC, type ChangeEvent } from 'react';
import type { GoodnessOfFitResult, QQPlotPoint, AnalysisResult } from './types';
import { ConfigProvider, Radio, Space, Typography, Divider, Button, Drawer, message, Input } from 'antd';
import { useTranslation } from 'react-i18next';
import DataInputSection from './components/DataInputSection';
import AnalysisResultSection from './components/AnalysisResultSection';
import AIModelChat from './components/AIModelChat';
import TutorialSection from './components/TutorialSection';
import AIDataGenerateDialog from './components/AIDataGenerateDialog';
import { darkTheme, lightTheme } from './theme';
import {
  calculateBasicStats,
  parseCSVContent,
  generateDistributionData,
  calculateMLE,
  calculateMoM,
  calculateConfidenceInterval,
  calculateWilsonConfidenceInterval,
  calculateMLEForDistributions,
  calculateGammaMoM,
  calculateBootstrapConfidenceInterval,
  analyzeDistribution,
  performROHEAnalysis,
  performGoodnessOfFitTest,
  generateQQPlotData
} from './utils';

const App: FC = () => {
  const { t, i18n } = useTranslation();
  const [activeTab, setActiveTab] = useState('basic');
  const [inputMethod, setInputMethod] = useState('upload');
  const [data, setData] = useState<number[]>([]);
  const [analysisResult, setAnalysisResult] = useState<AnalysisResult>({});
  const [goodnessOfFitResult, setGoodnessOfFitResult] = useState<GoodnessOfFitResult | null>(null);
  const [qqPlotData, setQQPlotData] = useState<QQPlotPoint[]>([]);
  const [currentView, setCurrentView] = useState<'analysis' | 'tutorial'>('analysis');
  const [isUserUploadedData, setIsUserUploadedData] = useState(false);
  const [isAutoGenerated, setIsAutoGenerated] = useState(false); // 标记是否为自动生成

  // 主题、设置和抽屉状态
  const [theme, setTheme] = useState<'dark' | 'light'>('dark');
  const [drawerOpen, setDrawerOpen] = useState(false);
  
  // AI数据生成对话框状态
  const [aiDialogOpen, setAiDialogOpen] = useState(false);

  // 当前语言
  // 确保i18n正确初始化，默认使用中文
  const [currentLanguage, setCurrentLanguage] = useState(i18n.language || 'zh');
  
  // 监听语言变化事件，确保UI状态与i18n语言同步
  useEffect(() => {
    const handleLanguageChange = (lng: string) => {
      setCurrentLanguage(lng.split('-')[0]);
    };

    i18n.on('languageChanged', handleLanguageChange);
    handleLanguageChange(i18n.language); // 设置初始值

    return () => {
      i18n.off('languageChanged', handleLanguageChange);
    };
  }, [i18n]);

  // API配置状态
  const [apiKey, setApiKey] = useState('');
  const [model, setModel] = useState('qwen-plus');

  // 初始化主题
  useEffect(() => {
    const savedTheme = localStorage.getItem('app-theme') as 'dark' | 'light' | null;
    if (savedTheme) {
      setTheme(savedTheme);
      // 应用保存的主题
      applyTheme(savedTheme);
    } else {
      // 默认应用暗色主题
      setTheme('dark');
      applyTheme('dark');
    }
  }, []);

  // 应用主题的辅助函数
  const applyTheme = (newTheme: 'dark' | 'light') => {
    const root = document.documentElement;
    if (newTheme === 'light') {
      // 应用VSCode Light主题的CSS变量
      root.style.setProperty('--monokai-bg', '#ffffff');
      root.style.setProperty('--monokai-bg-dark', '#ffffff');
      root.style.setProperty('--monokai-bg-light', '#f3f3f3');
      root.style.setProperty('--monokai-bg-lighter', '#ffffff');
      root.style.setProperty('--monokai-fg', '#000000');
      root.style.setProperty('--monokai-fg-dim', '#6c6c6c');
      root.style.setProperty('--monokai-orange', '#007acc');
      root.style.setProperty('--monokai-yellow', '#c79100');
      root.style.setProperty('--monokai-green', '#107c10');
      root.style.setProperty('--monokai-blue', '#007acc');
      root.style.setProperty('--monokai-purple', '#007acc');
      root.style.setProperty('--monokai-pink', '#d13438');
      root.style.setProperty('--monokai-gray', '#6c6c6c');
      root.style.setProperty('--monokai-overlay', 'rgba(0, 0, 0, 0.45)');
      root.style.setProperty('--monokai-glass', 'rgba(255, 255, 255, 0.85)');
      root.style.setProperty('--monokai-shadow', '0 4px 20px rgba(0, 0, 0, 0.08)');
    } else {
      // 应用VSCode Dark主题的CSS变量
      root.style.setProperty('--monokai-bg', '#1e1e1e');
      root.style.setProperty('--monokai-bg-dark', '#1e1e1e');
      root.style.setProperty('--monokai-bg-light', '#252526');
      root.style.setProperty('--monokai-bg-lighter', '#2d2d30');
      root.style.setProperty('--monokai-fg', '#cccccc');
      root.style.setProperty('--monokai-fg-dim', '#8c8c8c');
      root.style.setProperty('--monokai-orange', '#fd971f');
      root.style.setProperty('--monokai-yellow', '#dcdcaa');
      root.style.setProperty('--monokai-green', '#4ec9b0');
      root.style.setProperty('--monokai-blue', '#4fc3f7');
      root.style.setProperty('--monokai-purple', '#4fc3f7');
      root.style.setProperty('--monokai-pink', '#f44747');
      root.style.setProperty('--monokai-gray', '#8c8c8c');
      root.style.setProperty('--monokai-overlay', 'rgba(0, 0, 0, 0.8)');
      root.style.setProperty('--monokai-glass', 'rgba(30, 30, 30, 0.85)');
      root.style.setProperty('--monokai-shadow', '0 4px 20px rgba(0, 0, 0, 0.3)');
    }
  };

  // 主题切换处理函数
  const toggleTheme = () => {
    const newTheme = theme === 'dark' ? 'light' : 'dark';
    setTheme(newTheme);
    localStorage.setItem('app-theme', newTheme);
    applyTheme(newTheme);
  };

  // 语言切换处理函数
  const changeLanguage = (language: string) => {
    i18n.changeLanguage(language);
    setCurrentLanguage(language);
  };

  // 加载API配置
  useEffect(() => {
    const savedConfig = localStorage.getItem('aliyunApiConfig');
    if (savedConfig) {
      try {
        const { apiKey: savedKey, model: savedModel } = JSON.parse(savedConfig);
        setApiKey(savedKey || '');
        setModel(savedModel || 'qwen-plus');
      } catch (error) {
        console.error('Failed to load API config:', error);
      }
    }
  }, []);

  // 保存API密钥的函数将在后续实现

  // 处理数据分析
  const analyzeData = () => {
    if (data.length === 0) return;
    const basicStats = calculateBasicStats(data);
    const mleParams = calculateMLE(data);
    const momParams = calculateMoM(data);

    // 集成新增的统计分析功能
    const confidenceInterval = calculateConfidenceInterval(data);

    // 假设数据是二项分布的结果（0或1），计算Wilson置信区间
    const successCount = data.filter(val => val === 1).length;
    const totalCount = data.length;
    const wilsonInterval = calculateWilsonConfidenceInterval(successCount, totalCount);

    // 计算多种分布的MLE参数估计
    const distributionsMLE = calculateMLEForDistributions(data);

    // 计算Gamma分布的矩估计
    const gammaMoM = calculateGammaMoM(basicStats.mean, basicStats.variance);

    // 计算小样本Bootstrap置信区间
    const bootstrapInterval = calculateBootstrapConfidenceInterval(data);

    // 执行ROHE分析
    const roheAnalysis = performROHEAnalysis(data);

    // 计算分布特征分析（偏度、峰度、正态性检验等）
    const distributionAnalysis = analyzeDistribution(data);

    // 计算分布拟合优度检验
    const fitTestResult = performGoodnessOfFitTest(data);
    setGoodnessOfFitResult(fitTestResult);

    // 生成Q-Q图数据
    const qqData = generateQQPlotData(data);
    setQQPlotData(qqData);

    // 添加用户特定例子的数据（用于演示）
    const userExamples = {
      meanConfidenceInterval: calculateConfidenceInterval(new Array(27).fill(1478), 0.95, 36 * 36),
      wilsonIntervalExample: calculateWilsonConfidenceInterval(40, 100, 0.95)
    };

    setAnalysisResult({
      ...basicStats,
      mleParams,
      momParams,
      confidenceInterval,
      wilsonInterval,
      distributionsMLE,
      gammaMoM,
      bootstrapInterval,
      roheAnalysis,
      distributionAnalysis,
      userExamples
    });
  };

  // 处理文件上传
  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      const content = event.target?.result as string;
      try {
        const parsedData = parseCSVContent(content);
        setData(parsedData);
        setIsUserUploadedData(true);
        message.success(t('data.uploadSuccess'));
      } catch (error) {
        console.error(t('fileError.title'), error);
        alert(t('fileError.message'));
      }
    };
    reader.readAsText(file);
  };

  // 处理分布生成
  const handleDistributionGenerate = (type: string, customParams?: { sampleSize?: number; [key: string]: any }) => {
    const { sampleSize, ...distParams } = customParams || {};
    const params = {
      type,
      params: distParams || {},
      sampleSize: sampleSize || 1000
    };

    if (!distParams || Object.keys(distParams).length === 0) {
      switch (type) {
        case 'normal':
          params.params = { mean: 0, stdDev: 1 };
          break;
        case 'uniform':
          params.params = { min: 0, max: 1 };
          break;
        case 'exponential':
          params.params = { lambda: 1 };
          break;
        case 'poisson':
          params.params = { rate: 5 };
          break;
      }
    }

    const generatedData = generateDistributionData(params);
    setData(generatedData);
    setIsUserUploadedData(true);
    setIsAutoGenerated(false); // 用户手动生成
    message.success(t('data.generateSuccess'));
  };

  // 处理AI生成数据 - 打开对话框
  const handleAIGenerateData = () => {
    setAiDialogOpen(true);
  };

  // 处理AI生成的数据
  const handleAIGeneratedData = (generatedData: number[]) => {
    if (generatedData && generatedData.length > 0) {
      setData(generatedData);
      setIsUserUploadedData(true);
      setIsAutoGenerated(false);
      message.success(t('data.aiGenerateSuccess'));
    }
  };

  // 处理清除数据
  const handleClearData = () => {
    setData([]);
    setAnalysisResult({});
    setIsUserUploadedData(false);
    setIsAutoGenerated(false);
  };

  // 数据变化时自动分析
  useEffect(() => {
    if (data.length > 0) {
      analyzeData();
    }
  }, [data]);

  // 首次加载时生成示例数据
  useEffect(() => {
    if (data.length === 0) {
      const params = {
        type: 'normal',
        params: { mean: 50, stdDev: 15 },
        sampleSize: 1000
      };
      const exampleData = generateDistributionData(params);
      setData(exampleData);
      setIsAutoGenerated(true); // 标记为自动生成
    }
  }, []);

  return (
    <ConfigProvider theme={theme === 'dark' ? darkTheme : lightTheme}>
      <div className="min-h-screen">
      {/* Hero Section - 全屏 */}
      <section className="hero-section relative">
        {/* 背景装饰 */}
        <div className="hero-bg-decoration">
          <div className="hero-bg-circle"></div>
          <div className="hero-bg-circle"></div>
          <div className="hero-bg-circle"></div>
        </div>


        {/* Hero 内容 */}
        <div className="hero-content">
          <h1 className="hero-title">
            <span style={{ color: 'var(--monokai-orange)' }}>{t('app.title')}</span> {t('appInfo.webApp')}
          </h1>
          <p className="hero-subtitle">
            {t('app.subtitle')}
          </p>
          <div className="hero-buttons">
            <button
              onClick={() => {
                setCurrentView('analysis');
                // 自动滚动到分析区域
                setTimeout(() => {
                  const analysisSection = document.querySelector('.analysis-section');
                  if (analysisSection) {
                    analysisSection.scrollIntoView({ behavior: 'smooth' });
                  }
                }, 100);
              }}
              className="hero-primary-btn"
            >
              <i className="fa fa-rocket mr-2"></i>
              {t('app.nav.analysis')}
            </button>
            <button
              onClick={() => {
                setCurrentView('tutorial');
                // 自动滚动到教程区域
                setTimeout(() => {
                  const tutorialSection = document.querySelector('.tutorial-section');
                  if (tutorialSection) {
                    tutorialSection.scrollIntoView({ behavior: 'smooth' });
                  }
                }, 100);
              }}
              className="hero-secondary-btn"
            >
              <i className="fa fa-book mr-2"></i>
              {t('tutorial.title')}
            </button>
          </div>
        </div>
      </section>

      {/* 主内容区域 */}
      <main className="flex-grow bg-monokai">
        <div className="container mx-auto px-4 py-8">
          {/* 数据分析视图 */}
          {currentView === 'analysis' && (
            <div className="analysis-section grid grid-cols-1 lg:grid-cols-3 gap-6">
              <div className="lg:col-span-2 space-y-12">
                <DataInputSection
                  inputMethod={inputMethod}
                  setInputMethod={setInputMethod}
                  handleFileUpload={handleFileUpload}
                  handleDistributionGenerate={handleDistributionGenerate}
                  handleAIGenerateData={handleAIGenerateData}
                  handleClearData={handleClearData}
                  data={data}
                  isUserUploadedData={isUserUploadedData}
                  isAutoGenerated={isAutoGenerated}
                />
                {data.length > 0 && (
                  <AnalysisResultSection
                    activeTab={activeTab}
                    setActiveTab={setActiveTab}
                    analysisResult={analysisResult}
                    data={data}
                    goodnessOfFitResult={goodnessOfFitResult}
                    qqPlotData={qqPlotData}
                  />
                )}
              </div>

              {/* 侧边栏：AI助手和数据信息 */}
              <div className="space-y-6">
                {/* 数据概览 */}
                <div className="bg-monokai-light rounded-2xl p-6 border border-monokai shadow-monokai">
                  <h3 className="text-lg font-bold mb-4 flex items-center" style={{ color: 'var(--monokai-fg)' }}>
                    <div className="p-2 rounded-lg mr-3" style={{ backgroundColor: 'var(--monokai-blue)', color: 'var(--monokai-bg)' }}>
                      <i className="fa fa-database"></i>
                    </div>
                    {t('appInfo.dataOverview')}
                  </h3>
                  <div className="space-y-4">
                    <div className="p-4 rounded-xl bg-monokai border border-monokai">
                      <div className="flex items-center justify-between">
                        <div>
                          <p className="text-sm font-medium" style={{ color: 'var(--monokai-blue)' }}>{t('appInfo.dataPoints')}</p>
                          <p className="text-3xl font-bold" style={{ color: 'var(--monokai-fg)' }}>{data.length}</p>
                        </div>
                        <div className="p-3 rounded-full" style={{ backgroundColor: 'var(--monokai-blue)', color: 'var(--monokai-bg)' }}>
                          <i className="fa fa-chart-line"></i>
                        </div>
                      </div>
                    </div>

                    <div className="p-4 rounded-xl bg-monokai border border-monokai">
                      <div className="flex items-center justify-between">
                        <div>
                          <p className="text-sm font-medium" style={{ color: 'var(--monokai-green)' }}>{t('appInfo.dataRange')}</p>
                          <p className="text-lg font-semibold" style={{ color: 'var(--monokai-fg)' }}>
                            {data.length > 0
                              ? `${Math.min(...data).toFixed(2)} - ${Math.max(...data).toFixed(2)}`
                              : '--'
                            }
                          </p>
                        </div>
                        <div className="p-3 rounded-full" style={{ backgroundColor: 'var(--monokai-green)', color: 'var(--monokai-bg)' }}>
                          <i className="fa fa-arrows-alt-h"></i>
                        </div>
                      </div>
                    </div>

                    <div className="p-4 rounded-xl bg-monokai border border-monokai">
                      <div className="flex items-center justify-between">
                        <div>
                          <p className="text-sm font-medium" style={{ color: 'var(--monokai-purple)' }}>{t('appInfo.dataType')}</p>
                          <p className="text-lg font-semibold" style={{ color: 'var(--monokai-fg)' }}>
                            {data.length > 0 ? t('appInfo.numericData') : '--'}
                          </p>
                        </div>
                        <div className="p-3 rounded-full" style={{ backgroundColor: 'var(--monokai-purple)', color: 'var(--monokai-bg)' }}>
                          <i className="fa fa-hashtag"></i>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                {/* AI助手 */}
                <AIModelChat analysisResult={analysisResult} data={data} />
              </div>
            </div>
          )}

          {/* 教程视图 */}
          {currentView === 'tutorial' && (
            <TutorialSection />
          )}
        </div>
      </main>


      {/* 美化版页脚 - 整合底部信息 */}
      <footer className="bg-monokai-dark border-t border-monokai py-12">
        <div className="container mx-auto px-4">
          <div className="text-center">

            
            {/* 副标题区域 */}
            <div className="mb-6">
              <h3 className="text-xl font-semibold mb-3" style={{ color: 'var(--monokai-fg)' }}>
                {t('appInfo.footerTitle')}
              </h3>
              <p className="text-lg mb-4" style={{ color: 'var(--monokai-cyan)' }}>
                {t('appInfo.footerSubtitle')}
              </p>
            </div>
            
            {/* 版权信息 */}
            <div className="mb-4">
              <p className="text-sm" style={{ color: 'var(--monokai-gray)' }}>
                {t('app.footer')}
              </p>
            </div>
            
            {/* 特色标签 */}
            <div className="feature-tags">
              <span className="feature-tag">
                <span className="feature-tag-icon">🚀</span>
                {t('appInfo.modernDesignText')}
              </span>
              <span className="feature-tag">
                <span className="feature-tag-icon">🤖</span>
                {t('appInfo.aiDrivenText')}
              </span>
              <span className="feature-tag">
                <span className="feature-tag-icon">📊</span>
                {t('appInfo.dataVisualizationText')}
              </span>
              <span className="feature-tag">
                <span className="feature-tag-icon">⚡</span>
                {t('appInfo.highPerformanceText')}
              </span>
            </div>
          </div>
          
          {/* 社交媒体链接 */}
          <div className="flex justify-center space-x-4 mt-8">
            <a href="https://github.com/A1motoro/Analyzer_for_AIE1901" target="_blank" rel="noopener noreferrer"
              className="p-3 rounded-lg bg-monokai-light hover:bg-monokai text-monokai-gray hover:text-monokai-fg transition">
              <i className="fa fa-github text-xl"></i>
            </a>
            <a href="#" className="p-3 rounded-lg bg-monokai-light hover:bg-monokai text-monokai-gray hover:text-monokai-fg transition">
              <i className="fa fa-twitter text-xl"></i>
            </a>
            <a href="#" className="p-3 rounded-lg bg-monokai-light hover:bg-monokai text-monokai-gray hover:text-monokai-fg transition">
              <i className="fa fa-linkedin text-xl"></i>
            </a>
          </div>
        </div>
      </footer>

      {/* 右侧功能抽屉切换按钮 - 美化版 */}
      <button
        onClick={() => setDrawerOpen(true)}
        className="drawer-trigger-button"
        style={{
          position: 'fixed',
          right: '0',
          top: '50%',
          transform: 'translateY(-50%)',
          zIndex: 1000,
          padding: '16px 8px',
          backgroundColor: 'var(--monokai-purple)',
          color: 'var(--monokai-bg)',
          border: 'none',
          borderTopLeftRadius: '16px',
          borderBottomLeftRadius: '16px',
          boxShadow: '0 4px 20px rgba(0, 0, 0, 0.3), 0 0 0 2px rgba(79, 195, 247, 0.1)',
          transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
          cursor: 'pointer',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          gap: '8px',
        }}
        onMouseEnter={(e) => {
          e.currentTarget.style.transform = 'translateY(-50%) translateX(-4px)';
          e.currentTarget.style.backgroundColor = 'var(--monokai-orange)';
          e.currentTarget.style.boxShadow = '0 6px 24px rgba(0, 0, 0, 0.4), 0 0 0 4px rgba(253, 151, 31, 0.2)';
        }}
        onMouseLeave={(e) => {
          e.currentTarget.style.transform = 'translateY(-50%)';
          e.currentTarget.style.backgroundColor = 'var(--monokai-purple)';
          e.currentTarget.style.boxShadow = '0 4px 20px rgba(0, 0, 0, 0.3), 0 0 0 2px rgba(79, 195, 247, 0.1)';
        }}
        title={t('appInfo.openPanel')}
      >
        <i className="fa fa-cog" style={{ fontSize: '18px' }}></i>
        <span style={{ 
          fontSize: '12px', 
          fontWeight: '600',
          writingMode: 'vertical-rl',
          textOrientation: 'mixed',
          letterSpacing: '2px'
        }}>
          {t('appInfo.systemSettings')}
        </span>
      </button>

      {/* 右侧功能抽屉 - 集成设置 */}
      <Drawer
        title={
          <div style={{ 
            display: 'flex', 
            alignItems: 'center', 
            gap: '12px',
            fontSize: '18px',
            fontWeight: '600',
            color: 'var(--monokai-fg)'
          }}>
            <i className="fa fa-cog" style={{ color: 'var(--monokai-purple)' }}></i>
            <span>{t('appInfo.systemSettings')}</span>
          </div>
        }
        placement="right"
        onClose={() => setDrawerOpen(false)}
        open={drawerOpen}
        width={420}
        bodyStyle={{
          padding: '24px',
          background: theme === 'dark' ? 'var(--monokai-bg-light)' : 'var(--monokai-bg-lighter)',
          overflowY: 'auto',
        }}
        headerStyle={{
          background: theme === 'dark' ? 'var(--monokai-bg-lighter)' : 'var(--monokai-bg-light)',
          borderBottom: theme === 'dark' ? '1px solid var(--monokai-bg-lighter)' : '1px solid var(--monokai-gray)',
        }}
      >
        <Space direction="vertical" size="large" style={{ width: '100%' }}>
          {/* 快速功能 */}
          <div>
            <Typography.Title level={5} style={{ color: 'var(--monokai-fg)', marginBottom: '16px' }}>
              <i className="fa fa-bolt mr-2" style={{ color: 'var(--monokai-blue)' }}></i>
              {t('appInfo.quickFunctions')}
            </Typography.Title>
            <Space direction="vertical" size="middle" style={{ width: '100%' }}>
              {/* 教程按钮 */}
              <Button
                type="default"
                block
                icon={<i className="fa fa-book mr-2"></i>}
                onClick={() => {
                  setCurrentView('tutorial');
                  setDrawerOpen(false);
                }}
                style={{
                  textAlign: 'left',
                  height: '48px',
                  color: 'var(--monokai-blue)',
                  borderColor: 'var(--monokai-blue)',
                  background: 'transparent',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'flex-start',
                }}
                className="hover:bg-monokai-blue hover:text-monokai-bg transition-all duration-200"
              >
                <span>{t('appInfo.tutorial')}</span>
              </Button>
            </Space>
          </div>

          <Divider style={{
            borderColor: theme === 'dark' ? 'var(--monokai-bg-lighter)' : 'var(--monokai-gray)',
            margin: '24px 0'
          }} />

          {/* 主题设置 */}
          <div>
            <Typography.Title level={5} style={{ color: 'var(--monokai-fg)', marginBottom: '16px' }}>
              <i className="fa fa-paint-brush mr-2" style={{ color: 'var(--monokai-orange)' }}></i>
              {t('settings.theme')}
            </Typography.Title>
            <Radio.Group
              value={theme}
              onChange={() => toggleTheme()}
              style={{ width: '100%' }}
            >
              <Space direction="vertical" style={{ width: '100%' }}>
                <div
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    padding: '14px',
                    border: `2px solid ${theme === 'dark' ? 'var(--monokai-orange)' : 'transparent'}`,
                    borderRadius: '12px',
                    background: theme === 'dark' ? 'var(--monokai-bg)' : 'transparent',
                    cursor: 'pointer',
                    transition: 'all 0.2s ease',
                  }}
                  onClick={() => {
                    if (theme !== 'dark') toggleTheme();
                  }}
                  onMouseEnter={(e) => {
                    if (theme !== 'dark') {
                      e.currentTarget.style.borderColor = 'var(--monokai-orange)';
                      e.currentTarget.style.background = 'var(--monokai-bg)';
                    }
                  }}
                  onMouseLeave={(e) => {
                    if (theme !== 'dark') {
                      e.currentTarget.style.borderColor = 'transparent';
                      e.currentTarget.style.background = 'transparent';
                    }
                  }}
                >
                  <Radio value="dark" style={{ marginRight: '12px' }} />
                  <div style={{ flex: 1 }}>
                    <Space>
                      <span style={{ fontSize: '18px' }}>🌙</span>
                      <Typography.Text strong style={{ color: 'var(--monokai-fg)' }}>
                        {t('settings.dark')}
                      </Typography.Text>
                    </Space>
                    <Typography.Text style={{
                      fontSize: '12px',
                      color: 'var(--monokai-gray)',
                      display: 'block',
                      marginTop: '4px'
                    }}>
                      {t('settings.darkDesc')}
                    </Typography.Text>
                  </div>
                </div>

                <div
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    padding: '14px',
                    border: `2px solid ${theme === 'light' ? 'var(--monokai-blue)' : 'transparent'}`,
                    borderRadius: '12px',
                    background: theme === 'light' ? 'var(--monokai-bg)' : 'transparent',
                    cursor: 'pointer',
                    transition: 'all 0.2s ease',
                  }}
                  onClick={() => {
                    if (theme !== 'light') toggleTheme();
                  }}
                  onMouseEnter={(e) => {
                    if (theme !== 'light') {
                      e.currentTarget.style.borderColor = 'var(--monokai-blue)';
                      e.currentTarget.style.background = 'var(--monokai-bg)';
                    }
                  }}
                  onMouseLeave={(e) => {
                    if (theme !== 'light') {
                      e.currentTarget.style.borderColor = 'transparent';
                      e.currentTarget.style.background = 'transparent';
                    }
                  }}
                >
                  <Radio value="light" style={{ marginRight: '12px' }} />
                  <div style={{ flex: 1 }}>
                    <Space>
                      <span style={{ fontSize: '18px' }}>☀️</span>
                      <Typography.Text strong style={{ color: 'var(--monokai-fg)' }}>
                        {t('settings.light')}
                      </Typography.Text>
                    </Space>
                    <Typography.Text style={{
                      fontSize: '12px',
                      color: 'var(--monokai-gray)',
                      display: 'block',
                      marginTop: '4px'
                    }}>
                      {t('settings.lightDesc')}
                      <br />
                      <span style={{ color: '#f92672' }}>⚠️ {t('settings.lightWarning')}</span>
                    </Typography.Text>
                  </div>
                </div>
              </Space>
            </Radio.Group>
          </div>

          <Divider style={{
            borderColor: theme === 'dark' ? 'var(--monokai-bg-lighter)' : 'var(--monokai-gray)',
            margin: '24px 0'
          }} />

          {/* 语言设置 */}
          <div>
            <Typography.Title level={5} style={{ color: 'var(--monokai-fg)', marginBottom: '16px' }}>
              <i className="fa fa-language mr-2" style={{ color: 'var(--monokai-green)' }}></i>
              {t('settings.language')}
            </Typography.Title>
            <Radio.Group
              value={currentLanguage}
              onChange={(e) => changeLanguage(e.target.value)}
              style={{ width: '100%' }}
            >
              <Space direction="vertical" style={{ width: '100%' }}>
                <div
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    padding: '14px',
                    border: `2px solid ${currentLanguage === 'zh' ? 'var(--monokai-green)' : 'transparent'}`,
                    borderRadius: '12px',
                    background: currentLanguage === 'zh' ? 'var(--monokai-bg)' : 'transparent',
                    cursor: 'pointer',
                    transition: 'all 0.2s ease',
                  }}
                  onClick={() => changeLanguage('zh')}
                  onMouseEnter={(e) => {
                    if (currentLanguage !== 'zh') {
                      e.currentTarget.style.borderColor = 'var(--monokai-green)';
                      e.currentTarget.style.background = 'var(--monokai-bg)';
                    }
                  }}
                  onMouseLeave={(e) => {
                    if (currentLanguage !== 'zh') {
                      e.currentTarget.style.borderColor = 'transparent';
                      e.currentTarget.style.background = 'transparent';
                    }
                  }}
                >
                  <Radio value="zh" style={{ marginRight: '12px' }} />
                  <div style={{ flex: 1 }}>
                    <Space>
                      <span style={{ fontSize: '18px' }}>🇨🇳</span>
                      <Typography.Text strong style={{ color: 'var(--monokai-fg)' }}>
                        {t('settings.chinese')}
                      </Typography.Text>
                    </Space>
                  </div>
                </div>

                <div
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    padding: '14px',
                    border: `2px solid ${currentLanguage === 'en' ? 'var(--monokai-blue)' : 'transparent'}`,
                    borderRadius: '12px',
                    background: currentLanguage === 'en' ? 'var(--monokai-bg)' : 'transparent',
                    cursor: 'pointer',
                    transition: 'all 0.2s ease',
                  }}
                  onClick={() => changeLanguage('en')}
                  onMouseEnter={(e) => {
                    if (currentLanguage !== 'en') {
                      e.currentTarget.style.borderColor = 'var(--monokai-blue)';
                      e.currentTarget.style.background = 'var(--monokai-bg)';
                    }
                  }}
                  onMouseLeave={(e) => {
                    if (currentLanguage !== 'en') {
                      e.currentTarget.style.borderColor = 'transparent';
                      e.currentTarget.style.background = 'transparent';
                    }
                  }}
                >
                  <Radio value="en" style={{ marginRight: '12px' }} />
                  <div style={{ flex: 1 }}>
                    <Space>
                      <span style={{ fontSize: '18px' }}>🇺🇸</span>
                      <Typography.Text strong style={{ color: 'var(--monokai-fg)' }}>
                        {t('settings.english')}
                      </Typography.Text>
                    </Space>
                  </div>
                </div>
              </Space>
            </Radio.Group>
          </div>

          <Divider style={{
            borderColor: theme === 'dark' ? 'var(--monokai-bg-lighter)' : 'var(--monokai-gray)',
            margin: '24px 0'
          }} />

          {/* API配置 */}
          <div>
            <Typography.Title level={5} style={{ color: 'var(--monokai-fg)', marginBottom: '16px' }}>
              <i className="fa fa-key mr-2" style={{ color: 'var(--monokai-purple)' }}></i>
              {t('api.title')}
            </Typography.Title>
            <Space direction="vertical" size="middle" style={{ width: '100%' }}>
              {/* API Key输入 */}
              <div>
                <label htmlFor="apiKey" style={{ 
                  display: 'block',
                  fontSize: '13px',
                  fontWeight: '500',
                  color: 'var(--monokai-fg)',
                  marginBottom: '8px'
                }}>
                  {t('api.apiKey')}
                </label>
                <Input.Password
                  id="apiKey"
                  value={apiKey}
                  onChange={(e) => setApiKey(e.target.value)}
                  placeholder={t('api.apiKeyPlaceholder')}
                  style={{
                    background: theme === 'dark' ? 'var(--monokai-bg)' : 'white',
                    borderColor: theme === 'dark' ? 'var(--monokai-bg-lighter)' : '#d9d9d9',
                    color: 'var(--monokai-fg)',
                  }}
                />
              </div>

              {/* 模型选择 */}
              <div>
                <label htmlFor="model" style={{ 
                  display: 'block',
                  fontSize: '13px',
                  fontWeight: '500',
                  color: 'var(--monokai-fg)',
                  marginBottom: '8px'
                }}>
                  {t('api.modelSelect')}
                </label>
                <select
                  id="model"
                  value={model}
                  onChange={(e) => setModel(e.target.value)}
                  style={{
                    width: '100%',
                    padding: '8px 12px',
                    borderRadius: '6px',
                    border: `1px solid ${theme === 'dark' ? 'var(--monokai-bg-lighter)' : '#d9d9d9'}`,
                    background: theme === 'dark' ? 'var(--monokai-bg)' : 'white',
                    color: 'var(--monokai-fg)',
                    fontSize: '14px',
                    cursor: 'pointer',
                  }}
                >
                  <option value="qwen-plus">{t('api.qwenPlus')}</option>
                  <option value="qwen-max">{t('api.qwenMax')}</option>
                  <option value="qwen-turbo">{t('api.qwenTurbo')}</option>
                </select>
              </div>

              {/* 保存按钮 */}
              <Button
                type="primary"
                block
                icon={<i className="fa fa-info-circle mr-2"></i>}
                onClick={() => {
                  setCurrentView('tutorial');
                  setDrawerOpen(false);
                  // 自动滚动到教程区域
                  setTimeout(() => {
                    const tutorialSection = document.querySelector('.tutorial-section');
                    if (tutorialSection) {
                      tutorialSection.scrollIntoView({ behavior: 'smooth' });
                    }
                  }, 100);
                }}
                style={{
                  height: '40px',
                  backgroundColor: 'var(--monokai-purple)',
                  borderColor: 'var(--monokai-purple)',
                }}
                className="hover:opacity-90 transition-all duration-200"
              >
                {t('api.save')}
              </Button>

              {/* API保存成功提示将在后续实现 */}
            </Space>
          </div>

          <Divider style={{
            borderColor: theme === 'dark' ? 'var(--monokai-bg-lighter)' : 'var(--monokai-gray)',
            margin: '24px 0'
          }} />

          {/* 其他设置 */}
          <div>
            <Typography.Title level={5} style={{ color: 'var(--monokai-fg)', marginBottom: '16px' }}>
              <i className="fa fa-cog mr-2" style={{ color: 'var(--monokai-gray)' }}></i>
              {t('settings.other')}
            </Typography.Title>
            <Space direction="vertical" style={{ width: '100%' }}>
              <Button
                type="text"
                block
                icon={<i className="fa fa-refresh mr-2"></i>}
                onClick={() => {
                  localStorage.removeItem('app-theme');
                  window.location.reload();
                }}
                style={{
                  textAlign: 'left',
                  height: '40px',
                  color: 'var(--monokai-gray)',
                  border: 'none',
                  background: 'transparent',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'flex-start',
                }}
                className="hover:bg-monokai hover:text-monokai-fg transition-all duration-200"
              >
                {t('appInfo.resetDefault')}
              </Button>
            </Space>
          </div>
        </Space>
      </Drawer>
      </div>

      {/* AI数据生成对话框 */}
      <AIDataGenerateDialog
        open={aiDialogOpen}
        onClose={() => setAiDialogOpen(false)}
        onGenerate={handleAIGeneratedData}
      />
    </ConfigProvider>
  );
};

export default App;
