name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: List build directory
        run: |
          echo "📁 Build directory contents:"
          ls -la build/
          echo "📁 Static JS directory contents:"
          ls -la build/static/js/ || echo "static/js directory not found"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'
          retention-days: 1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Verify deployment
        run: |
          echo "Deployment URL: ${{ steps.deployment.outputs.page_url }}"
          echo "Verifying deployment..."
          if curl -f -s ${{ steps.deployment.outputs.page_url }} > /dev/null; then
            echo "✅ Main page accessible"
            # Check if JS file exists
            JS_URL="${{ steps.deployment.outputs.page_url }}/static/js/main.b186718e.js"
            if curl -f -s "$JS_URL" > /dev/null; then
              echo "✅ JavaScript file accessible: $JS_URL"
            else
              echo "❌ JavaScript file NOT accessible: $JS_URL"
            fi
          else
            echo "❌ Main page NOT accessible"
          fi
